services:
  database:
    image: mariadb:latest
    container_name: dnd_database
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: example
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - 3309:3306
volumes:
  data: